language: python
python:
        - "2.7"

before_install:
        - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
        - tar xzf google-cloud-sdk.tar.gz
        - wget https://github.com/boot2docker/boot2docker-cli/releases/download/v1.4.1/boot2docker-v1.4.1-linux-amd64
        - wget http://download.virtualbox.org/virtualbox/4.3.20/virtualbox-4.3_4.3.20-96996~Ubuntu~precise_amd64.deb

install:
        - printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh
        - printf 'y\n' | ./google-cloud-sdk/bin/gcloud components update app
        - sudo apt-get update
        - sudo apt-get install linux-headers-2.6.32-042-generic
        - sudo apt-get install libsdl1.2debian libvpx1
        - sudo apt-get install dkms
        - sudo dpkg -i virtualbox-4.3_4.3.20-96996~Ubuntu~precise_amd64.deb
        - pip install PyOpenSSL

before_script:
        - chmod u+x ./boot2docker-v1.4.1-linux-amd64
        - rm -rf ~/VirtualBox\ VMs/boot2docker-vm
        - ./boot2docker-v1.4.1-linux-amd64 init -v
        - ./boot2docker-v1.4.1-linux-amd64 up
        - $(./boot2docker-v1.4.1-linux-amd64 shellinit)
        - ./google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
        - export CLOUDSDK_PYTHON_SITEPACKAGES=1
        - echo $CREDENTIALS_JSON > credentials.json
        - ./google-cloud-sdk/bin/gcloud auth activate-service-account $ACCOUNT --key-file credentials.json
        - rm credentials.json
        - ./google-cloud-sdk/bin/gcloud preview app deploy . --version hello-sample-appengine-vm-python

script: python test.py
