language: python
python:
        - "2.7"

before_install:
        #Set up remote docker
        - mkdir -p $HOME/.docker
        - echo $CA > $HOME/.docker/ca.pem
        - echo $CERT > $HOME/.docker/cert.pem
        - echo $KEY > $HOME/.docker/key.pem
        - export DOCKER_TLS_VERIFY=1
        - export DOCKER_CERT_PATH=$HOME/.docker
        - ls $DOCKER_CERT_PATH

        #Install gcloud
        - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
        - tar xzf google-cloud-sdk.tar.gz
        - printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh

        #Authenticate with gcloud
        - ./google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
        - export CLOUDSDK_PYTHON_SITEPACKAGES=1
        - echo $CREDENTIALS_JSON > credentials.json
        - ./google-cloud-sdk/bin/gcloud auth activate-service-account $ACCOUNT --key-file credentials.json

install:
        - printf 'y\n' | ./google-cloud-sdk/bin/gcloud components update app
        - pip install PyOpenSSL

        - printf '1\n' > gcloud preview app setup-managed-vms

script:
        - ./google-cloud-sdk/bin/gcloud preview app deploy . --version hello-sample-appengine-vm-python
        - python test.py
